# Generated by Django 4.2.2 on 2023-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellschedule',
            name='default_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='bellschedule',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
